// TODO: see if this page actually works after https://github.com/vercel/next.js/issues/55462 is resolved

"use client"

import * as Sentry from "@sentry/nextjs"
import Error from "next/error"
import { useEffect } from "react"

export default function GlobalError({ error }) {
  useEffect(() => {
    Sentry.captureException(error)
  }, [error])

  const isRefreshTokenError = error?.message?.includes("Refresh Token Not Found")

  return (
    <html lang="en">
      <body className="bg-black text-white">
        <div className="text-xl">Oops! Something went wrong.</div>
        <div className="mt-4 text-md text-gray-300">
          {isRefreshTokenError ? (
            "It looks like your cookies are stale. Try clearing your cookies just for catalog.fyi, and then refreshing the page. (You can look up instructions for how to clear cookies for a specific site with the device/browser you're using, so that you don't have to clear ALL your cookies and get logged out of everything you use.)"
          ) : (
            // @ts-ignore this file is generated by Sentry
            <Error />
          )}
        </div>
      </body>
    </html>
  )
}
