on: push

jobs:
  lint-job:
    runs-on: ubuntu-latest
    name: Lint
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install modules
        run: pnpm install
      - name: Run ESLint
        run: pnpm lint
